const JOBS_DATA = [
    {
        id: "rrb-technician-2026",
        title: "Railway RRB Technician (Grade I & III) Recruitment 2026",
        agency: "Railway Recruitment Boards (RRB)",
        category: "Railway",
        dateAdded: "2026-06-29",
        lastDate: "2026-07-29",
        vacancies: 6565,
        qualification: "Matriculation (10th) with ITI / Diploma / Degree in Engineering",
        ageLimit: "18-36 Years (Grade I), 18-33 Years (Grade III)",
        fee: "Gen/OBC/EWS: ₹500, SC/ST/Female/Ex-Servicemen: ₹250",
        status: "Apply Now",
        notificationUrl: "https://www.rrbcdg.gov.in/",
        applyUrl: "https://www.rrbapply.gov.in/",
        syllabusUrl: "#"
    },
    {
        id: "boi-credit-officer-2026",
        title: "Bank of India (BOI) Credit Officer Generalist Recruitment 2026",
        agency: "Bank of India (BOI)",
        category: "Bank",
        dateAdded: "2026-06-29",
        lastDate: "2026-07-20",
        vacancies: 779,
        qualification: "B.Com / M.Com / MBA / CA / ICWA from recognized university",
        ageLimit: "25-37 Years",
        fee: "Gen/OBC/EWS: ₹850, SC/ST/PWD: ₹175",
        status: "Apply Now",
        notificationUrl: "https://www.bankofindia.co.in/career",
        applyUrl: "https://www.bankofindia.co.in/career",
        syllabusUrl: "#"
    },
    {
        id: "upsc-advt-07-2026",
        title: "UPSC Drug Inspector, Joint Director & Various Posts (Advt 07/2026)",
        agency: "Union Public Service Commission (UPSC)",
        category: "UPSC",
        dateAdded: "2026-06-27",
        lastDate: "2026-07-17",
        vacancies: 450,
        qualification: "Bachelor Degree in Pharmacy / Engineering / Law (post-specific)",
        ageLimit: "30-35 Years (Post-wise limit)",
        fee: "Gen/OBC/EWS: ₹25, SC/ST/Female/PwBD: ₹0",
        status: "Apply Now",
        notificationUrl: "https://www.upsc.gov.in/sites/default/files/AdvtNo-07-2026-Engl-250626.pdf",
        applyUrl: "https://upsconline.nic.in/ora/",
        syllabusUrl: "#"
    },
    {
        id: "neet-ug-result-2026",
        title: "NTA NEET UG 2026 Entrance Examination Final Results & Score Card",
        agency: "National Testing Agency (NTA)",
        category: "Result",
        dateAdded: "2026-06-27",
        lastDate: "N/A",
        vacancies: 100000,
        qualification: "NEET UG 2026 Registered Candidates",
        ageLimit: "Min 17 Years",
        fee: "N/A",
        status: "Result Out",
        notificationUrl: "https://exams.nta.ac.in/NEET/",
        applyUrl: "https://exams.nta.ac.in/NEET/",
        syllabusUrl: "#"
    },
    {
        id: "sbi-po-2026",
        title: "State Bank of India (SBI) Probationary Officers (PO) Recruitment 2026",
        agency: "State Bank of India (SBI)",
        category: "Bank",
        dateAdded: "2026-06-25",
        lastDate: "2026-07-08",
        vacancies: 1500,
        qualification: "Graduation (Bachelor's Degree) in any discipline",
        ageLimit: "21-30 Years",
        fee: "Gen/OBC/EWS: ₹750, SC/ST/PWD: ₹0",
        status: "Apply Now",
        notificationUrl: "https://sbi.co.in/web/careers",
        applyUrl: "https://sbi.co.in/web/careers/current-openings",
        syllabusUrl: "#"
    },
    {
        id: "dsssb-assistant-teacher-2026",
        title: "DSSSB Assistant Teacher (Primary) & Nursery Post Recruitment",
        agency: "Delhi Subordinate Services Selection Board (DSSSB)",
        category: "Teaching",
        dateAdded: "2026-06-25",
        lastDate: "2026-07-25",
        vacancies: 1455,
        qualification: "12th Class with Diploma in Elementary Education (D.El.Ed) / B.Ed & CTET Pass",
        ageLimit: "Below 30 Years",
        fee: "Gen/OBC/EWS: ₹100, SC/ST/PH/Female: ₹0",
        status: "Apply Now",
        notificationUrl: "https://dsssb.delhi.gov.in/home",
        applyUrl: "https://dsssbonline.nic.in/",
        syllabusUrl: "#"
    },
    {
        id: "upsc-advt-06-2026",
        title: "UPSC Medical Officer, Geophysicist & Engineer Recruitment (Advt 06/2026)",
        agency: "Union Public Service Commission (UPSC)",
        category: "UPSC",
        dateAdded: "2026-06-24",
        lastDate: "2026-07-03",
        vacancies: 420,
        qualification: "MBBS / M.Sc in Geophysics / Degree in Engineering",
        ageLimit: "32-35 Years (Post-wise)",
        fee: "Gen/OBC/EWS: ₹25, SC/ST/Female: ₹0",
        status: "Last Date Soon",
        notificationUrl: "https://upsc.gov.in/whats-new",
        applyUrl: "https://upsconline.nic.in/ora/",
        syllabusUrl: "#"
    },
    {
        id: "indian-army-agniveer-rally-2026",
        title: "Indian Army Agniveer General Duty & Technical Rally Recruitment",
        agency: "Indian Army (Join Indian Army)",
        category: "Defence",
        dateAdded: "2026-06-22",
        lastDate: "2026-07-20",
        vacancies: 25000,
        qualification: "Class 8th / 10th / 12th Pass (based on specific Agniveer trade)",
        ageLimit: "17.5 - 21 Years",
        fee: "All Candidates: ₹250",
        status: "Apply Now",
        notificationUrl: "https://joinindianarmy.nic.in/",
        applyUrl: "https://joinindianarmy.nic.in/",
        syllabusUrl: "#"
    },
    {
        id: "ssc-mts-havaldar-2026",
        title: "SSC Multi-Tasking Staff (MTS) & Havaldar Online Form 2026",
        agency: "Staff Selection Commission (SSC)",
        category: "SSC",
        dateAdded: "2026-06-20",
        lastDate: "2026-06-30",
        vacancies: 8326,
        qualification: "Matriculation (10th Class) Pass from recognized Board",
        ageLimit: "18-25 Years or 18-27 Years (based on post)",
        fee: "Gen/OBC: ₹100, SC/ST/Female/ESM: ₹0",
        status: "Last Date Soon",
        notificationUrl: "https://ssc.gov.in/",
        applyUrl: "https://ssc.gov.in/home/apply",
        syllabusUrl: "#"
    },
    {
        id: "ugc-net-june-2026-admit",
        title: "NTA UGC NET June 2026 Exam Phase I Admit Card",
        agency: "National Testing Agency (NTA)",
        category: "Admit Card",
        dateAdded: "2026-06-21",
        lastDate: "2026-06-30",
        vacancies: 50000,
        qualification: "UGC NET June 2026 Registered Candidates",
        ageLimit: "JRF: Max 30 Years, Lectureship: No Age Limit",
        fee: "N/A",
        status: "Admit Card Out",
        notificationUrl: "https://ugcnet.nta.nic.in/",
        applyUrl: "https://ugcnet.nta.nic.in/",
        syllabusUrl: "#"
    }
];
