// Browser regression audit of every Assistant Teacher route against local files.
const fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
const {ROOT,siteFiles,parse}=require('./seo-html.cjs');const {routeRepositoryFixtures}=require('./lib/browser-fixture.cjs');
const files=siteFiles(),filter=process.argv[2]||'',pages=files.filter(p=>/^up-assistant-teacher\/.*index\.html$/.test(p)&&(!filter||(filter==='assistant-english'&&(p==='up-assistant-teacher/index.html'||p.startsWith('up-assistant-teacher/english/')))||(filter!=='assistant-english'&&p.includes(filter))));
const report={pages:[],failures:[]};
(async()=>{const browser=await chromium.launch({headless:true});let cursor=0,done=0;
try{await Promise.all(Array.from({length:4},async()=>{const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce',serviceWorkers:'block'});await context.addInitScript(()=>{sessionStorage.setItem('sj_auth_gate_skipped','1');localStorage.setItem('sjmaths_preferred_language','en');localStorage.setItem('sj_pref_lang','en');});const page=await context.newPage();const evidence=await routeRepositoryFixtures(page,{root:ROOT,files});while(cursor<pages.length){const file=pages[cursor++],row={file,states:[]},errorStart=evidence.errors.length,missingStart=evidence.missing.length;try{await page.goto('https://sjmaths.com/'+file.replace(/index.html$/,''),{waitUntil:'domcontentloaded',timeout:20000});await page.locator('#headerLangToggleBtn').waitFor({state:'visible',timeout:10000});const authOverlay=page.locator('#sj-auth-overlay');await authOverlay.waitFor({state:'visible',timeout:5000}).catch(()=>{});if(await authOverlay.isVisible()){await page.locator('#sj-skip-gate-btn').click();await authOverlay.waitFor({state:'hidden',timeout:5000}).catch(()=>{});}if(await page.locator('#upsc-page-data').count())await page.locator('#topic-content .study-tab-footer').waitFor({timeout:10000});
for(const lang of ['en','hi']){if(await page.evaluate(()=>document.documentElement.lang)!==lang)await page.locator('#headerLangToggleBtn').click({force:true});const tabs=await page.locator('.study-tabs .tab-btn:visible').count();for(let i=0;i<Math.max(tabs,1);i++){if(tabs)await page.locator('.study-tabs .tab-btn:visible').nth(i).click({force:true});const state=await page.evaluate(({lang})=>{const visible=e=>{for(let p=e;p;p=p.parentElement)if(getComputedStyle(p).display==='none'||getComputedStyle(p).visibility==='hidden')return false;return !!e.getClientRects().length};const root=document.querySelector('.topic-container,.syllabus-container,main')||document.body;const wrong=[...root.querySelectorAll(lang==='en'?'.lang-hi:not(.lang-en)':'.lang-en:not(.lang-hi)')].filter(visible).map(e=>e.textContent.trim().slice(0,90));const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node,leaks=[];while(node=walker.nextNode()){const p=node.parentElement;if(p.closest('script,style,noscript,.katex,.MathJax')||!visible(p))continue;if(lang==='en'&&/[\u0900-\u097f]/.test(node.textContent))leaks.push(node.textContent.trim().slice(0,110));}return{lang,actualLang:document.documentElement.lang,tab:document.querySelector('.tab-btn.active')?.dataset.tab,saved:[localStorage.getItem('sj_pref_lang'),localStorage.getItem('sjmaths_preferred_language')],wrong,leaks,overflow:Math.max(0,document.documentElement.scrollWidth-innerWidth),emptySubmit:!!document.querySelector('.btn-submit-test')&&!document.querySelector('.test-question-card'),content:document.querySelector('#topic-content')?.innerText.slice(0,80)}},{lang});row.states.push(state);if(state.wrong.length||state.leaks.length||state.saved.some(value=>value!==lang)||state.overflow>1||state.emptySubmit||state.actualLang!==lang)report.failures.push({file,...state});}}
row.errors=evidence.errors.slice(errorStart).filter(e=>!e.includes('Service Worker')&&!/Failed to load resource: net::ERR_(?:NAME_NOT_RESOLVED|CONNECTION_CLOSED|CONNECTION_RESET|TIMED_OUT)/.test(e));row.missing=evidence.missing.slice(missingStart);if(row.errors.length||row.missing.length)report.failures.push({file,errors:row.errors,missing:row.missing});}catch(e){row.error=e.message;report.failures.push({file,error:e.message});}report.pages.push(row);done++;if(done%25===0)console.log(`Language audit: ${done}/${pages.length} pages, ${report.failures.length} findings`);}await context.close();}));}finally{await browser.close();}fs.mkdirSync(path.join(ROOT,'scratch'),{recursive:true});fs.writeFileSync(path.join(ROOT,'scratch/assistant-language-browser.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({pages:report.pages.length,states:report.pages.reduce((n,p)=>n+p.states.length,0),findings:report.failures.length,examples:report.failures.slice(0,10)},null,2));if(report.failures.length)process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1});
