const test = require('node:test');
const assert = require('node:assert/strict');
const { inspectInlineScripts } = require('./lib/inline-script-integrity.cjs');
const { recoverRepeatedBodyPage } = require('./lib/recover-katex-expanded-pages.cjs');
const { exposeUpperPrimaryRuntimeGlobals } = require('./lib/up-upper-primary-runtime-globals.cjs');
test('checks classic scripts without executing them and excludes data, modules and external scripts', () => {
  const html = '<script>throw new Error("must not run");</script><script type="application/ld+json">{broken}</script><script type="module">import x from "x";</script><script src="x.js"></script><script type="text/javascript">const x = 1;</script>';
  const scripts = inspectInlineScripts(html);
  assert.equal(scripts.length, 2);
  assert.deepEqual(scripts.map(script => script.syntaxError), [null, null]);
});
test('shared Upper Primary runtime receives its checklist and complete test data on window', () => {
  const input = '<script>const TOPIC_STORAGE_KEY = \'checklist\'; const TOPIC_CHECKBOX_ID = \'topic-3\'; const testData = [{"question":"नाद","correct_index":0}];</script>';
  const output = exposeUpperPrimaryRuntimeGlobals(input);
  assert.equal(output, '<script>window.TOPIC_STORAGE_KEY = \'checklist\'; window.TOPIC_CHECKBOX_ID = \'topic-3\'; window.testData = [{"question":"नाद","correct_index":0}];</script>');
  assert.equal(exposeUpperPrimaryRuntimeGlobals(input.replace('const testData =', 'let testData =')), null);
  assert.equal(exposeUpperPrimaryRuntimeGlobals('<script>const testData = [];</script>'), null);
});
test('reports corrupt embedded documents and exact duplicates without rewriting source', () => {
  const html = '<script>const a = "\n<body><main>Lesson</main>";</script><script>const x=1;</script><script>const x=1;</script>';
  const scripts = inspectInlineScripts(html);
  assert.ok(scripts[0].syntaxError);
  assert.equal(scripts[0].nestedDocumentMarkup, true);
  assert.equal(scripts[2].duplicateOf, 1);
  assert.equal(scripts[1].duplicateOf, null);
});
test('KaTeX recovery preserves byte-identical repeated bodies and refuses content variants', () => {
  const head = '<html><head><title>अनुरक्षित</title><script type="application/ld+json">{}</script>';
  const injected = '<script>\n    document.addEventListener("DOMContentLoaded", function () {\n        if (typeof renderMathInElement === \'function\')';
  const body = '<body><main>पूरा पाठ</main><script type="application/json">{"q":1}</script></body>';
  const source = `${head}${injected}${body}${body}</head>${body}</html>`;
  const result = recoverRepeatedBodyPage(source, '<link rel="katex"><script>math();</script>');
  assert.ok(result);
  assert.equal(result.split(body).length - 1, 1);
  assert.ok(result.includes('<title>अनुरक्षित</title>'));
  assert.ok(result.includes('application/json'));
  assert.equal(inspectInlineScripts(result).filter(script => script.syntaxError).length, 0);
  assert.equal(recoverRepeatedBodyPage(source.replace('<main>पूरा पाठ</main>', '<main>बदला हुआ</main>', 1), '<link>'), null);
  assert.equal(recoverRepeatedBodyPage(source, ''), null);
});
test('KaTeX recovery keeps one verified complete document copy and ignores cache-buster differences', () => {
  const injected = '<script>\n    document.addEventListener("DOMContentLoaded", function () {\n        if (typeof renderMathInElement === \'function\')\n            renderMathInElement(document.body, {\n                delimiters: [\n                    { left: \'$\', right: \'$\', display: true },\n                    { left: \'\n</head>';
  const copy = version => `<body><main><h1>Polynomials</h1><p>Complete lesson</p><script src="/assets/app.js?v=${version}"></script></main></body></html>`;
  const source = `<html><head><title>Polynomials</title><script src="/katex.js"></script>${injected}<style>.lesson{color:green}</style>${copy('one')}, right: '\n</head>${copy('two')}, display: false },\n</head>${copy('three')}`;
  const result = recoverRepeatedBodyPage(source, '<script>renderMathInElement(document.body, {});</script>');
  assert.ok(result);
  assert.equal((result.match(/<body\b/g) || []).length, 1);
  assert.equal((result.match(/<\/html>/g) || []).length, 1);
  assert.ok(result.includes('<title>Polynomials</title>'));
  assert.ok(result.includes('<style>.lesson{color:green}</style>'));
  assert.ok(result.includes('Complete lesson'));
  assert.ok(!result.includes("{ left: '$', right: '$', display: true },"));
  const crlfResult = recoverRepeatedBodyPage(source.replace(/\n/g, '\r\n'), '<script>renderMathInElement(document.body, {});</script>');
  assert.ok(crlfResult?.includes('</script>\r\n</head><style>.lesson{color:green}</style>'));
  assert.equal(recoverRepeatedBodyPage(source.replace('Complete lesson', 'Changed lesson'), '<script>fixed</script>'), null);
});
test('KaTeX recovery rebuilds a valid shell around one identical body after an empty broken shell', () => {
  const body = '<body><main><h1>Moving Charges</h1><p>Complete physics lesson</p></main></body>';
  const stub = '<html><head><title>Moving Charges</title><script src="/assets/js/math-markup-compat.js"></script></body></html>, right: \'\n';
  const injected = '<script>\n    document.addEventListener("DOMContentLoaded", function () {\n        if (typeof renderMathInElement === \'function\')';
  const source = `${stub}${body}\n</html>\n${injected}\n</head>\n${body}\n</html>\n</html>\n${body}`;
  const katex = '<link rel="katex"><script>renderMathInElement(document.body, {});</script>';
  const result = recoverRepeatedBodyPage(source, katex);
  assert.ok(result);
  assert.equal((result.match(/<html\b/g) || []).length, 1);
  assert.equal((result.match(/<head\b/g) || []).length, 1);
  assert.equal((result.match(/<\/head>/g) || []).length, 1);
  assert.equal((result.match(/<body\b/g) || []).length, 1);
  assert.equal((result.match(/<\/body>/g) || []).length, 1);
  assert.equal((result.match(/<\/html>/g) || []).length, 1);
  assert.equal((result.match(/<h1>/g) || []).length, 1);
  assert.ok(result.includes('<title>Moving Charges</title>'));
  assert.ok(result.includes('Complete physics lesson'));
  assert.equal(recoverRepeatedBodyPage(source.replace('Complete physics lesson', 'Different lesson', 1), katex), null);
});
