import sys
import os

# We will import the structures by adding scratch to sys.path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from build_upsc_syllabus import (
    ancient_history, medieval_history, modern_history, art_and_culture,
    physical_geography, indian_geography, environment, polity, economy,
    science_tech, csat, clean_slug, get_item_slug, get_subsection_slug, get_subject_folder
)

subjects = {
    "anc": ancient_history,
    "med": medieval_history,
    "mod": modern_history,
    "art": art_and_culture,
    "pgeo": physical_geography,
    "igeo": indian_geography,
    "env": environment,
    "pol": polity,
    "eco": economy,
    "st": science_tech,
    "csat": csat
}

item_texts = {}
item_paths = {}

print("Scanning for duplications...")
duplicates_found = False

for prefix, data in subjects.items():
    subject_folder = get_subject_folder(prefix)
    for grp in data:
        subsection = grp["subsection"]
        for item in grp["items"]:
            # Check for exact text duplication
            if item in item_texts:
                print(f"DUPLICATE TEXT FOUND: '{item}' in both prefix {prefix} (subsection '{subsection}') and prefix {item_texts[item][0]} (subsection '{item_texts[item][1]}')")
                duplicates_found = True
            else:
                item_texts[item] = (prefix, subsection)
            
            # Check for path/slug duplication
            item_slug = get_item_slug(item)
            subsection_slug = get_subsection_slug(subsection, item)
            rel_path = f"{subject_folder}/{subsection_slug}/{item_slug}"
            
            if rel_path in item_paths:
                print(f"DUPLICATE PATH CONFLICT: '{rel_path}' generated by:")
                print(f"  1. Topic: '{item}' in prefix {prefix} (subsection '{subsection}')")
                print(f"  2. Topic: '{item_paths[rel_path][2]}' in prefix {item_paths[rel_path][0]} (subsection '{item_paths[rel_path][1]}')")
                duplicates_found = True
            else:
                item_paths[rel_path] = (prefix, subsection, item)

if not duplicates_found:
    print("SUCCESS: No text or path duplications found in the syllabus datasets!")
else:
    print("Finished scan with some duplication warnings.")
