import re
import os

ENG_DIR = r"c:\Users\sande\Documents\GitHub\sjmaths-website\upsc\ancient_history\HarappanIndus-Valley-Civilisation\Domestication-of-animals"

practice_raw_eng = [
    # 1. Zebu Cattle dominance
    ("With reference to the pastoral economy of the Indus Valley Civilisation, consider the following statements:\n1. Cattle (zebu) bones represent the largest percentage of faunal remains at almost all sites.\n2. Sheep and goats were reared together primarily for milk and wool.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Cattle (zebu) bones are the most dominant faunal remains (50-60%), and sheep and goats were reared in mixed herds for milk, meat, and wool."),
    # 2. Cow on seals
    ("Consider the following statements regarding the cow in Harappan culture:\n1. Humped bulls are highly prominent on steatite administrative seals.\n2. The female cow is depicted alongside the humped bull on several seals from Mohenjo-daro.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 0, "Statement 1 is correct. Statement 2 is incorrect: the female cow is completely absent from all known Harappan seals and iconography, which is a major contrast to the Rigvedic period."),
    # 3. Camel bones Kalibangan
    ("With reference to the beasts of burden in the Harappan civilization, consider the following statements:\n1. Camel bones showing adaptation to dry climates have been excavated in significant quantities at Kalibangan.\n2. Camels were the primary source of traction for ploughing agricultural fields in Punjab.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 0, "Statement 1 is correct. Statement 2 is incorrect: humped oxen (bulls) were the primary draft animals used for agricultural plough traction, not camels."),
    # 4. Dog-human burial Ropar
    ("Consider the following statements regarding burial practices in Harappan cities:\n1. A human burial containing a domestic dog buried alongside the deceased was excavated at Ropar.\n2. The practice of burying domestic pets with their owners was common across all major Harappan cemeteries.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 0, "Statement 1 is correct. Statement 2 is incorrect: the dog-human co-burial is unique to Ropar in Punjab and not found in other Harappan cemeteries."),
    # 5. Brick cat footprint Chanhudaro
    ("With reference to domestic pets in the Indus Valley Civilisation, consider the following statements:\n1. A wet clay brick with paw prints of a dog chasing a cat was discovered at Chanhudaro.\n2. Terracotta toys of dogs showing collar bands suggest they were kept as domestic pets.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Chanhudaro yielded a brick with paw prints showing a dog chasing a cat, and terracotta dog toys from Harappa show collars, proving their pet status."),
    # 6. Zebu classification
    ("Consider the following statements regarding the humped cattle of the Indus Valley Civilisation:\n1. Humped cattle are scientifically classified as Bos indicus.\n2. The humped bull or zebu is carved with great detail and artistic realism on administrative seals.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Humped cattle are Bos indicus and were carved with extreme realism on steatite seals."),
    # 7. Donkeys and camels
    ("With reference to overland trade networks of the Harappans, consider the following statements:\n1. Domestic asses (donkeys) were used as beasts of burden for transport across rocky terrains.\n2. Camel remains at Kalibangan suggest camels were utilized for desert trade routes.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Donkeys and camels served as pack animals for overland trade in arid and rocky regions (Baluchistan/Rajasthan)."),
    # 8. Pig bones consumption
    ("Consider the following statements regarding Harappan diets and zooarchaeological remains:\n1. High concentrations of domestic pig (Sus scrofa) bones are found in refuse heaps near urban residential sectors.\n2. Pigs were kept in urban dump yards, feeding on organic waste and providing a source of meat.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Pig bones are common in urban refuse middens, indicating pigs consumed organic waste and were slaughtered for meat."),
    # 9. herding
    ("With reference to Harappan sheep and goat herding, consider the following statements:\n1. Pastoral groups reared sheep and goats together in mixed herds to exploit complementary resources.\n2. Sheep were sheared for wool, whereas goats were primarily kept for milk and meat.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Sheep and goats were kept together; sheep provided wool, and both provided milk and meat."),
    # 10. Terracotta dogs
    ("Consider the following statements regarding terracotta figurines in Harappan sites:\n1. Toy figurines representing dogs have been excavated showing collar bands.\n2. Terracotta models of horses showing spoked-wheeled chariots have been found at Mohenjo-daro.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 0, "Statement 1 is correct. Statement 2 is incorrect: horses and spoked-wheeled chariots are completely absent from Harappan terracotta art."),
    # 11. Lion vs Tiger
    ("With reference to felines depicted in Mature Harappan art, consider the following statements:\n1. The tiger is a common motif on seals, often shown in scenes with men in trees.\n2. The Asiatic lion is frequently depicted on seals as a symbol of royal power.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 0, "Statement 1 is correct. Statement 2 is incorrect: the lion is absent or extremely rare on seals, unlike the tiger which is highly common."),
    # 12. Pashupati seal
    ("Which of the following wild animals are depicted on the famous 'Pashupati Seal' of Mohenjo-daro?\n1. Tiger\n2. Elephant\n3. Rhinoceros\n4. Lion\nSelect the correct answer using the code given below:", ["1, 2 and 3 only", "1, 2 and 4 only", "2, 3 and 4 only", "1, 2, 3 and 4"], 0, "The Pashupati seal depicts a tiger, an elephant, a rhinoceros, and a buffalo surrounding the deity, with two deer below the throne. The lion is absent."),
    # 13. Gharial
    ("Consider the following statements regarding the representation of aquatic fauna in Harappan art:\n1. The gharial or fish-eating crocodile is commonly depicted on pottery, amulets, and seals.\n2. Marine fish and tortoises are depicted on painted pottery at coastal sites like Lothal.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Gharials represent riverine fauna on seals/pottery, and marine species are common in coastal Lothal art."),
    # 14. Makran coast fish
    ("With reference to the maritime trade of the Harappans, consider the following statements:\n1. Dried and salted marine fish were traded from coastal outposts on the Makran coast to inland cities like Harappa.\n2. Fish bone assemblages at Harappa include species native only to the Arabian Sea.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Zooarchaeological analysis of fish bones at Harappa shows they include marine species traded from the Makran coast (800 km away)."),
    # 15. Copper fish hooks
    ("Consider the following statements regarding fishing technology in Harappan sites:\n1. Large numbers of copper and bronze fish hooks have been excavated at Mohenjo-daro and Lothal.\n2. The Harappans relied exclusively on bone hooks due to the scarcity of metals.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 0, "Statement 1 is correct. Statement 2 is incorrect: metal hooks of copper and bronze were widely used for fishing in both rivers and seas."),
    # 16. Shell craft
    ("With reference to the manufacturing of shell objects, consider the following statements:\n1. Coastal sites like Nageshwar and Balakot specialized in the procurement and carving of marine chank shells.\n2. Marine shell bangles, ladles, and inlay work were traded from coastal workshops to inland cities.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Nageshwar and Balakot were dedicated shell-craft centers that traded finished goods (bangles, ladles) inland."),
    # 17. Ivory workshops
    ("Consider the following statements regarding ivory utilization in the Indus Valley Civilisation:\n1. Lothal has yielded ivory workshop remains, including unworked elephant tusks and waste flakes.\n2. Ivory was exported from the Indus Valley (Meluhha) to Mesopotamia as a luxury trade commodity.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Lothal has an ivory workshop, and Akkadian texts list ivory from Meluhha (Indus valley) as a premium import."),
    # 18. Copper arrowheads
    ("With reference to Harappan hunting practices, consider the following statements:\n1. Copper arrowheads and clay slingshots were used to hunt wild boar, deer, and birds.\n2. Wild animal bones represent the main source of daily protein in large urban centers.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 0, "Statement 1 is correct. Statement 2 is incorrect: domesticated livestock bones make up over 80% of urban assemblages; hunting wild game was secondary."),
    # 19. Bone cut marks
    ("Consider the following statements regarding zooarchaeological analysis of animal bones:\n1. Sharp cut marks and scrapes at joints indicate butchery and meat processing for human consumption.\n2. Charring or burning of bones shows they were roasted or cooked.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Cut marks and charring are direct osteological evidence of slaughtering and cooking animals for food."),
    # 20. Cattle age-at-death
    ("With reference to the economic use of cattle, consider the following statements:\n1. Zooarchaeological mortality profiles showing cattle living to old age suggest they were used for milk and agricultural traction.\n2. Cattle were slaughtered uniformly at very young ages, indicating they were raised exclusively for beef.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 0, "Statement 1 is correct. Keeping cattle until old age proves they were valued for their milk and labor (pulling carts/ploughs) rather than quick meat."),
    # 21. Sheep age-at-death
    ("Consider the following statements regarding the herding of sheep in Harappan cities:\n1. Sheep were kept to mature ages to harvest maximum wool yields over several years.\n2. Woven wool and cotton textiles were primary industrial exports of the Harappans.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Zooarchaeological age profiles confirm sheep were kept to mature ages to shear wool, which was woven into textiles for trade."),
    # 22. Surkotada horse bones
    ("With reference to the site of Surkotada in Gujarat, consider the following statements:\n1. J.P. Joshi excavated Mature-Late Harappan layers that yielded bones claimed to be the true horse.\n2. Hungarian zooarchaeologist Sandor Bokonyi confirmed the identification of these bones as Equus caballus.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. J.P. Joshi excavated horse bones at Surkotada, and Bokonyi verified them as belonging to the true horse (Equus caballus)."),
    # 23. Richard Meadow counter-argument
    ("Consider the following statements regarding the counter-arguments in the horse controversy:\n1. Scholar Richard Meadow argues that the Surkotada bones belong to the wild ass (khur) or domestic donkey.\n2. The wild ass (Equus hemionus) is native to the Rann of Kutch and shares skeletal similarities with the horse.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Meadow contested the horse claim, asserting the bones belong to the native wild ass (khur), which looks similar osteologically."),
    # 24. Absence of horse on seals
    ("With reference to the cultural role of the horse, consider the following statements:\n1. The horse is completely absent from all Mature Harappan seals and terracotta art.\n2. The horse holds a central religious and economic place in Rigvedic culture, unlike in Harappan iconography.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. The horse's absence on seals shows it was not culturally integrated in Harappa, representing a sharp shift from Vedic culture."),
    # 25. Climate transition
    ("Consider the following statements regarding the environmental changes in the Late Harappan phase:\n1. Disappearance of water-loving fauna like rhinoceros and elephant bones from refuse dumps indicates climatic drying.\n2. Late Harappan assemblages show an increase in dry-adapted sheep and goat remains.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. The shift in bone assemblages from wet-climate species to dry-adapted ruminants confirms environmental desiccation around 1900 BCE."),
    # 26. Transhumance
    ("With reference to pastoral nomadic groups in Gujarat, consider the following statements:\n1. They engaged in seasonal migrations (transhumance) between dry plains and wet hills to secure pastures.\n2. They supplied urban Harappan centers with milk, wool, hides, and draft animals in exchange for grains and metal tools.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Seasonal pastoral migration (transhumance) was vital for herd survival and maintained symbiotic trade with cities."),
    # 27. Ruminant bone percentages
    ("Consider the following statements regarding zooarchaeological statistics at Harappan sites:\n1. Domesticated cattle, buffalo, sheep, and goat bones constitute over 70% to 80% of faunal remains at most urban sites.\n2. Bones of wild deer and antelope are completely absent from all urban kitchen middens.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 1, "Statement 1 is correct. Statement 2 is incorrect: wild deer bones are present, indicating supplementary hunting, though it was minor."),
    # 28. Marine resources Balakot
    ("With reference to coastal subsistence strategies at Balakot, consider the following statements:\n1. Excavations show high consumption of marine fish and sea turtles, indicating a marine-dominant diet.\n2. The site was a major center for herding humped camels for maritime shipment.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 1, "Statement 1 is correct. Statement 2 is incorrect: Balakot was a coastal shell-craft and sea-fishing center, not a camel herding outpost."),
    # 29. Terracotta model carts
    ("Consider the following statements regarding transportation in the Indus Valley Civilisation:\n1. Terracotta toy models of carts show they were designed to be pulled by humped oxen.\n2. These toy models feature solid, spoke-less clay wheels matching track ruts found in streets.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Bullock carts with solid hubless wheels were the primary bulk overland transport system, as confirmed by toys and ruts."),
    # 30. Steatite seal carving
    ("With reference to Harappan glyptic art, consider the following statements:\n1. Seals were carved out of soft talcose rock called steatite and then fired to glaze them.\n2. The humped bull or zebu was the single most common animal depicted on seals.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 1, "Statement 1 is correct. Statement 2 is incorrect: the mythological one-horned unicorn was the most common motif, not the humped bull."),
    # 31. Wild animals in refuse
    ("Consider the following statements regarding wild fauna remains in Harappan refuse heaps:\n1. Bones of rhinoceros, wild boar, and various deer species indicate supplementary hunting.\n2. Wild birds like peacocks, jungle fowl, and ducks were also hunted for food.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Refuse piles yield bones of wild boar, deer, and birds, proving that hunting supplemented agricultural diets."),
    # 32. Composite creatures
    ("With reference to Harappan seal iconography, consider the following statements:\n1. Seals sometimes depict composite creatures, such as a three-headed beast combining a bull, unicorn, and ibex.\n2. Human-faced quadrupeds with unicorn horns suggest complex mythological and religious beliefs.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Composite and chimerical creatures are highly common on seals, indicating administrative or mythological icons."),
    # 33. River turtle shells
    ("Consider the following statements regarding kitchen refuse at Harappa:\n1. Heavy concentrations of river turtle shells with burn marks indicate they were boiled and consumed.\n2. Turtles were kept in domestic ponds as sacred household guardians and never eaten.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 1, "Statement 1 is correct. Statement 2 is incorrect: burned shell fragments prove turtles were harvested from rivers and cooked for food."),
    # 34. Equidae family teeth
    ("With reference to dental remains at Kalibangan, consider the following statements:\n1. Excavations yielded jaw fragments and teeth belonging to the Equidae (horse/ass) family.\n2. These dental remains conclusively prove that the true domestic horse was used for agriculture in Rajasthan.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 1, "Statement 1 is correct. Statement 2 is incorrect: these teeth are highly debated and cannot conclusively differentiate between horses and asses."),
    # 35. Domestic pets models
    ("Consider the following statements regarding household pets in Harappan cities:\n1. Terracotta figurines show dogs with collars, proving they were domesticated for guarding and companionship.\n2. Domestic cats are represented by terracotta figurines showing cats catching mice.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 1, "Statement 1 is correct. Statement 2 is incorrect: cats are proven by brick paw prints (Chanhudaro), but cat toy figurines are extremely rare or absent."),
    # 36. Rarity of metal sickles
    ("With reference to harvesting tools in Harappan fields, consider the following statements:\n1. Chert blades set in wooden handles were the primary tools used as sickles to harvest grains.\n2. Bronze and copper sickles were mass-produced in urban factories to harvest rabi crops.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 1, "Statement 1 is correct. Statement 2 is incorrect: metal sickles were extremely rare, as chert (stone) was the primary material for sickles."),
    # 37. Water buffalo roles
    ("Consider the following statements regarding the water buffalo (Bubalus bubalis) in Harappa:\n1. Buffaloes were domesticated and used for milk, meat, and traction in wet alluvial soils.\n2. Buffalo bones show high concentrations in water-logged coastal outposts of Gujarat.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. The water buffalo was domesticated and exploited for dairy, meat, and traction in wet fields."),
    # 38. Peacock depiction
    ("With reference to wild birds in Harappan art, consider the following statements:\n1. The peacock is frequently painted on pottery and modeled as terracotta figurines, showing its symbolic value.\n2. Peacocks are depicted on seals as draft birds pulling the chariots of deities.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 1, "Statement 1 is correct. Statement 2 is incorrect: peacocks were never depicted as draft birds pulling chariots (chariots themselves were unknown)."),
    # 39. Ivory import Mesopotamia
    ("Consider the following statements regarding cuneiform inscriptions of Mesopotamia:\n1. Tablets list ivory items imported from the land of 'Meluhha', which is identified as the Indus Valley.\n2. Raw elephant tusks were shipped via Persian Gulf transit ports to Mesopotamian workshops.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Mesopotamian records list ivory objects and tusks imported from Meluhha (the Indus valley) via the Gulf."),
    # 40. Circular brick pens
    ("With reference to livestock management in rural Gujarat, consider the following statements:\n1. Circular stone and brick enclosures found at rural sites functioned as corrals to pen sheep, goats, or cattle at night.\n2. These enclosures were built to protect domesticated herds from wild predators like tigers and leopards.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Circular corrals protect livestock from nocturnal predators, representing structured rural pastoral management."),
    # 41. Fish hook material
    ("Consider the following statements regarding Harappan fishing gear:\n1. Fish hooks excavated at riverine and coastal sites were made of copper and bronze.\n2. Iron fish hooks were widely traded from Gangetic sites during the Mature Harappan phase.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 1, "Statement 1 is correct. Statement 2 is incorrect: iron was completely unknown to the Harappans, who relied on copper/bronze for metal hooks."),
    # 42. Animal sacrifice
    ("With reference to ritual evidence at Harappan sites, consider the following statements:\n1. Clay altars at Kalibangan containing animal bones and ash suggest cattle sacrifices.\n2. The 'Pashupati Seal' depicts a deity performing a horse sacrifice.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 1, "Statement 1 is correct. Statement 2 is incorrect: the Pashupati seal shows a seated yogic figure surrounded by wild animals, not a sacrifice scene."),
    # 43. Rigvedic vs Harappan
    ("Consider the following statements regarding the contrast between Harappan and Rigvedic societies:\n1. Harappan seals are dominated by bulls and unicorns, while Rigvedic culture is highly horse-centric.\n2. Harappan civilization was urban and commercial, while Rigvedic society was pastoral and rural.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. These represent key differences in economy, settlement types, and faunal focus between the two periods."),
    # 44. Wild ass biological
    ("With reference to the wild ass (khur) of Kutch, consider the following statements:\n1. The scientific name of the wild ass is Equus hemionus.\n2. Its bones are osteologically very similar to the true horse, causing identification controversies.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. The wild ass (Equus hemionus) is native to Kutch and its skeletal similarity to the horse fuels the Surkotada debate."),
    # 45. Dog skeletons in graves
    ("Consider the following statements regarding burial offerings in Harappan graves:\n1. Skeletons of domestic dogs are found in almost every single excavated Harappan grave.\n2. Ropar is the only site where a dog was found buried directly beneath the owner's body.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Statement 2 is correct. Statement 1 is incorrect: dog co-burials are extremely rare, with Ropar being the only verified site."),
    # 46. Wildlife depictions environment
    ("With reference to the ancient environment of the Indus Valley, consider the following statements:\n1. The frequent depiction of swampy species like rhinoceros and tigers on seals indicates a humid, wet climate.\n2. The complete absence of desert animals like camels on seals shows the valley was completely forested.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Statement 1 is correct. Statement 2 is incorrect: camels existed (proven by bones at Kalibangan) but were simply not chosen as seal motifs."),
    # 47. Bone tool manufacturing
    ("Consider the following statements regarding manufacturing from wild animal remains:\n1. Antlers of wild deer (sambar/chital) were collected from forests to manufacture needles, awls, and pins.\n2. Antlers show signs of sawing and carving in workshops at Harappa and Mohenjo-daro.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Deer antlers were collected and processed in urban workshops to make bone implements and tools."),
    # 50. Late Harappan ruralization
    ("With reference to the late Harappan pastoral shifts, consider the following statements:\n1. The decline of urban granaries led to a decentralization of herding and local dairy production.\n2. Late Harappan populations in Gujarat focused heavily on herding goats and sheep rather than large cattle.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. The transition to rural settings was accompanied by herding smaller, drought-adapted sheep and goats."),
    # 48. Buffalo combat
    ("Consider the following statements regarding buffalo representations on seals:\n1. Seals sometimes depict a water buffalo in combat with a tiger, representing nature myths.\n2. Buffalo horn motifs are depicted on the headgear of deities, indicating sacred value.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 2, "Both statements are correct. Buffaloes are shown in combat scenes, and horned headgear is a diagnostic feature of Harappan deities on seals."),
    # 49. Barter weights
    ("With reference to exchange systems in Harappan trade, consider the following statements:\n1. Standardized chert weights, mostly cubic, were used to weigh commodities during barter transactions.\n2. Trade of pastoral items like wool and hides relied on metallic coins with animal engravings.\nWhich of the statements given above is/are correct?", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"], 1, "Statement 1 is correct. Statement 2 is incorrect: coins did not exist; barter backed by standardized chert weights was the system.")
]

practice_raw_hin = [
    # 1. Zebu Cattle dominance
    ("सिंधु घाटी सभ्यता की पशुपालन अर्थव्यवस्था के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. मवेशियों (जेबू) की हड्डियाँ लगभग सभी स्थलों पर प्राणि-अवशेषों में सबसे अधिक प्रतिशत में मिली हैं।\n2. भेड़ और बकरियों को मुख्य रूप से दूध और ऊन के लिए एक साथ पाला जाता था।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। मवेशियों (जेबू) की हड्डियाँ सबसे अधिक मिली हैं (50-60%), और भेड़-बकरियों को दूध, मांस तथा ऊन के लिए पाला जाता था।"),
    # 2. Cow on seals
    ("हड़प्पा संस्कृति में गाय के संबंध में निम्नलिखित कथनों पर विचार कीजिए:\n1. सेलखड़ी की प्रशासनिक मुहरों पर कूबड़ वाले बैल का अंकन अत्यधिक मिलता है।\n2. मोहनजोदड़ो की कई मुहरों पर कूबड़ वाले बैल के साथ मादा गाय का भी अंकन किया गया है।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 0, "कथन 1 सही है। कथन 2 गलत है क्योंकि मुहरों और कलाकृतियों पर गाय का चित्रण पूरी तरह से अनुपस्थित है, जो ऋग्वैदिक काल से अलग है।"),
    # 3. Camel bones Kalibangan
    ("हड़प्पा सभ्यता में भारवाहक पशुओं के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. कालीबंगन से शुष्क जलवायु के अनुकूल ऊंट की हड्डियाँ महत्वपूर्ण मात्रा में मिली हैं।\n2. पंजाब में कृषि खेतों की जुताई के लिए ऊंट ही मुख्य श्रम पशु थे।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 0, "कथन 1 सही है। कथन 2 गलत है क्योंकि जुताई के लिए मुख्य रूप से कूबड़ वाले बैलों का उपयोग किया जाता था, ऊंटों का नहीं।"),
    # 4. Dog-human burial Ropar
    ("हड़प्पा शहरों में शवाधान प्रथाओं के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. पंजाब के रोपण से एक कब्र मिली है जहाँ मनुष्य के कंकाल के साथ पालतू कुत्ते को दफनाया गया था।\n2. पालतू जानवरों को उनके मालिकों के साथ दफनाने की यह प्रथा सभी हड़प्पा कब्रिस्तानों में आम थी।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 0, "कथन 1 सही है। कथन 2 गलत है क्योंकि मनुष्य के साथ कुत्ते को दफनाने की यह प्रथा केवल रोपण में मिली है, अन्य कब्रिस्तानों में नहीं।"),
    # 5. Brick cat footprint Chanhudaro
    ("सिंधु घाटी सभ्यता में पालतू जानवरों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. चन्हुदड़ो से गीली मिट्टी की एक ईंट मिली है जिस पर बिल्ली का पीछा करते कुत्ते के पैरों के निशान अंकित हैं।\n2. मिट्टी के खिलौना कुत्तों पर गले में पट्टा दिखाना यह दर्शाता है कि उन्हें पालतू बनाया गया था।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। चन्हुदड़ो की ईंट पर पंजों के निशान और खिलौना कुत्तों के गले में पट्टा पालतू पेट्स होने की पुष्टि करते हैं।"),
    # 6. Zebu classification
    ("सिंधु घाटी सभ्यता के कूबड़ वाले मवेशियों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. कूबड़ वाले मवेशियों को वैज्ञानिक रूप से 'बॉस इंडिकस' (Bos indicus) के रूप में वर्गीकृत किया गया है।\n2. मुहरों पर कूबड़ वाले बैल का चित्रण बहुत ही सजीव और कलात्मक बारीकी से किया गया है।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। कूबड़ वाले बैल (जेबू) का वैज्ञानिक नाम बॉस इंडिकस है और मुहरों पर इनका अत्यधिक कलात्मक चित्रण मिलता है।"),
    # 7. Donkeys and camels
    ("हड़प्पा वासियों के थलीय व्यापारिक नेटवर्क के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. पथरीले रास्तों पर सामान ढोने के लिए घरेलू गधों का उपयोग भारवाहक पशुओं के रूप में किया जाता था।\n2. कालीबंगन से प्राप्त ऊंट की हड्डियाँ दर्शाती हैं कि ऊंटों का उपयोग मरुस्थलीय व्यापार मार्गों पर होता था।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। गधे और ऊंट शुष्क एवं पहाड़ी क्षेत्रों में मालवाहक पशुओं के रूप में व्यापारिक नेटवर्क के मुख्य हिस्से थे।"),
    # 8. Pig bones consumption
    ("हड़प्पा कालीन आहार और प्राणि-अवशेषों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. आवासीय कचरे के ढेरों में पालतू सूअर (Sus scrofa) की हड्डियाँ प्रचुर मात्रा में मिली हैं।\n2. सूअर शहरों के कचरा क्षेत्रों में जैविक कचरा खाते थे और सस्ता मांस प्रदान करते थे।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। सूअर की हड्डियाँ कचरे के ढेरों से मिली हैं, जो मांस उपभोग और अपशिष्ट खाने वाले पशु के रूप में उनकी भूमिका को दर्शाती हैं।"),
    # 9. herding
    ("हड़प्पा भेड़ और बकरियों के पालन के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. खानाबदोश चरवाहे पूरक संसाधनों के उपयोग के लिए भेड़ और बकरियों को एक साथ मिश्रित झुंडों में पालते थे।\n2. भेड़ों से मुख्यतः ऊन प्राप्त किया जाता था, जबकि बकरियों को मांस और दूध के लिए पाला जाता था।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। मिश्रित झुंडों में दोनों को पाला जाता था; भेड़ों से ऊन तथा दोनों से दूध और मांस प्राप्त होता था।"),
    # 10. Terracotta dogs
    ("हड़प्पा स्थलों से प्राप्त मिट्टी के खिलौनों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. कुत्तों की मिट्टी की आकृतियों में उनके गले में पट्टा (collar band) बना हुआ मिला है।\n2. मोहनजोदड़ो से रथ खींचते हुए घोड़ों के मिट्टी के मॉडल भी प्रचुर मात्रा में मिले हैं।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 0, "कथन 1 सही है। कथन 2 गलत है क्योंकि हड़प्पा कला में घोड़े और रथ खींचते घोड़ों के चित्र पूर्णतः अनुपस्थित हैं।"),
    # 11. Lion vs Tiger
    ("परिपक्व हड़प्पा कला में चित्रित हिंसक बिल्ली प्रजातियों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. मुहरों पर बाघ एक आम प्रतीक है, जिसे अक्सर पेड़ पर बैठे मनुष्य के साथ दिखाया गया है।\n2. शेर हड़प्पा प्रशासनिक मुहरों पर सबसे आम प्रतीक था जो राजकीय सत्ता को दर्शाता था।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 0, "कथन 1 सही है। कथन 2 गलत है क्योंकि मुहरों पर शेर का चित्रण अत्यंत दुर्लभ/अनुपस्थित है, जबकि बाघ बहुत आम है।"),
    # 12. Pashupati seal
    ("मोहनजोदड़ो की प्रसिद्ध 'पशुपति मुहर' पर निम्नलिखित में से किन जंगली जानवरों का चित्रण मिलता है?\n1. बाघ\n2. हाथी\n3. गैंडा\n4. शेर\nनीचे दिए गए कूट का प्रयोग कर सही उत्तर चुनिए:", ["1, 2 और 3 केवल", "1, 2 और 4 केवल", "2, 3 और 4 केवल", "1, 2, 3 और 4"], 0, "पशुपति मुहर पर केंद्रीय आकृति के चारों ओर बाघ, हाथी, गैंडा और भैंस खड़े हैं। शेर इस पर अनुपस्थित है।"),
    # 13. Gharial
    ("हड़प्पा कला में जलीय जीवों के चित्रण के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. बर्तनों, ताबीजों और मुहरों पर घड़ियाल (मछली खाने वाले मगरमच्छ) का चित्रण बहुत आम है।\n2. तटीय स्थलों जैसे लोथल के बर्तनों पर समुद्री मछलियों और कछुओं के सुंदर चित्र मिलते हैं।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। घड़ियाल नदी पारिस्थितिकी का और समुद्री मछलियां/कछुए लोथल की तटीय कला का प्रतीक हैं।"),
    # 14. Makran coast fish
    ("हड़प्पा सभ्यता के समुद्री व्यापार के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. बलूचिस्तान के मकरान तट से सूखी और नमकीन समुद्री मछली अंतर्देशीय शहरों (जैसे हड़प्पा) में व्यापार के लिए भेजी जाती थी।\n2. हड़प्पा से मिली मछलियों की हड्डियों में ऐसी प्रजातियाँ शामिल हैं जो केवल अरब सागर में पाई जाती हैं।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। वैज्ञानिक विश्लेषण पुष्टि करता है कि अंतर्देशीय हड़प्पा में समुद्री मछली मकरान तट (800 किमी दूर) से आयात की जाती थी।"),
    # 15. Copper fish hooks
    ("हड़प्पा स्थलों से मिले मछली पकड़ने के उपकरणों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. मोहनजोदड़ो और लोथल से तांबे और कांसे के मछली पकड़ने के हुक (hooks) बड़ी संख्या में मिले हैं।\n2. धातु की कमी के कारण हड़प्पा वासी मछली पकड़ने के लिए केवल हड्डियों के हुक पर निर्भर थे।\nउपर्युक्त कथनों में से कौन-sa/se सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 0, "कथन 1 सही है। कथन 2 गलत है क्योंकि मछली पकड़ने के लिए तांबे और कांसे के कांटे (hooks) व्यापक रूप से उपयोग होते थे।"),
    # 16. Shell craft
    ("शंख की वस्तुओं के निर्माण के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. नागेश्वर और बालाकोट जैसी तटीय बस्तियाँ समुद्री शंख (Turbinella pyrum) एकत्र करने और तराशने में माहिर थीं।\n2. तटीय कार्यशालाओं से बनी शंख की चूड़ियाँ, चमचे और पच्चीकारी की वस्तुएं अंतर्देशीय शहरों में व्यापार के लिए भेजी जाती थीं।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। नागेश्वर और बालाकोट विशेष शंख शिल्प केंद्र थे जो अपनी निर्मित वस्तुओं का व्यापार अंतर्देशीय शहरों में करते थे।"),
    # 17. Ivory workshops
    ("सिंधु घाटी सभ्यता में हाथीदांत के उपयोग के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. लोथल से हाथीदांत की कार्यशाला के अवशेष मिले हैं, जिसमें बिना काम किए दांत और कचरा टुकड़े शामिल हैं।\n2. मेसोपोटामिया को विलासिता की वस्तु के रूप में सिंधु घाटी (मेलुहा) से हाथीदांत का निर्यात किया जाता था।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। लोथल में हाथीदांत कारखाना था और मेसोपोटामियाई स्रोतों में मेलुहा से हाथीदांत के आयात के स्पष्ट संदर्भ हैं।"),
    # 18. Copper arrowheads
    ("हड़प्पा वासियों के शिकार प्रथाओं के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. जंगली सूअर, हिरण और पक्षियों का शिकार करने के लिए तांबे के बाणाग्र और मिट्टी की गुलेल की गोलियों का उपयोग होता था।\n2. बड़े शहरी केंद्रों में दैनिक प्रोटीन आहार का मुख्य स्रोत जंगली जानवरों का शिकार ही था।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 0, "कथन 1 सही है। कथन 2 गलत है क्योंकि प्रोटीन का मुख्य स्रोत पालतू पशु (मवेशी, भेड़-बकरी) थे, जंगली शिकार केवल सहायक था।"),
    # 19. Bone cut marks
    ("पशु हड्डियों के पुरातात्विक विश्लेषण के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. हड्डियों के जोड़ों पर तेज काटने और खरोंच के निशान मानव उपभोग के लिए मांस प्रसंस्करण (butchery) को दर्शाते हैं।\n2. हड्डियों का झुलसा या जला होना यह दिखाता है कि मांस को भूनकर या पकाकर खाया जाता था।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। हड्डियों पर काटने और जलने के निशान कसाईखाना प्रसंस्करण तथा पकाने की प्रत्यक्ष पुष्टि करते हैं।"),
    # 20. Cattle age-at-death
    ("मवेशियों के आर्थिक उपयोग के संबंध में, निम्नलिखित कथनों पर विचार कीजिए:\n1. मवेशियों की मृत्यु-आयु का प्रोफाइल यह दर्शाता है कि उन्हें बुढ़ापे तक पाला जाता था, जो दूध और श्रम उपयोग को सिद्ध करता है।\n2. मवेशियों को बहुत कम उम्र में मार दिया जाता था, जिससे पता चलता है कि उन्हें केवल गोमांस के लिए पाला जाता था।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 0, "कथन 1 सही है। मवेशियों को अधिक उम्र तक जीवित रखना कृषि श्रम (हल/गाड़ी) और दूध उत्पादन के लिए उनके उपयोग को सिद्ध करता है।"),
    # 21. Sheep age-at-death
    ("हड़प्पा शहरों में भेड़ों के पालन के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. भेड़ों को वयस्क/वृद्ध होने तक पाला जाता था ताकि कई वर्षों तक उनसे अधिकतम ऊन प्राप्त किया जा सके।\n2. बुने हुए ऊनी और सूती कपड़े हड़प्पा वासियों के प्रमुख औद्योगिक निर्यात उत्पाद थे।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। भेड़ों की अधिक उम्र की हड्डियां ऊन की कतरन का साक्ष्य हैं, जो कपड़ा उद्योग को सहारा देती थीं।"),
    # 22. Surkotada horse bones
    ("गुजरात के सुरकोटदा स्थल के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. जे.पी. जोशी ने सुरकोटदा के परिपक्व-उत्तर हड़प्पा स्तरों से ऐसी हड्डियां खोदीं जिन्हें घोड़े की हड्डियां कहा गया।\n2. हंगरी के प्राणि-विज्ञानी सैंडोर बोकोनी ने इन हड्डियों को वास्तविक घोड़े (Equus caballus) के रूप में पहचाना।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। जे.पी. जोशी ने सुरकोटदा से हड्डियां प्राप्त की थीं और बोकोनी ने उन्हें घोड़े (Equus caballus) के अवशेष माना था।"),
    # 23. Richard Meadow counter-argument
    ("घोड़े के विवाद में विपक्षी तर्कों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. रिचर्ड मीडो का तर्क है कि सुरकोटदा की हड्डियां वास्तव में जंगली गधे (khur) या पालतू गधे की हैं।\n2. जंगली गधा (Equus hemionus) कच्छ के रण का मूल निवासी है और इसकी हड्डियां घोड़े से बहुत मिलती हैं।\nउपर्युक्त कथनों में से कौन-sa/se सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। मीडो ने इन साक्ष्यों को खारिज कर इन्हें स्थानीय जंगली गधे (khur) की हड्डियां माना था।"),
    # 24. Absence of horse on seals
    ("हड़प्पा संस्कृति में घोड़े की सांस्कृतिक भूमिका के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. परिपक्व हड़प्पा मुहरों और टेराकोटा कला पर घोड़े का चित्रण पूर्णतः अनुपस्थित है।\n2. ऋग्वैदिक संस्कृति में घोड़े को केंद्रीय आर्थिक और धार्मिक महत्व प्राप्त था, जो हड़प्पा मुहर कला से भिन्न है।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। मुहरों पर घोड़े का चित्रण न मिलना यह दर्शाता है कि हड़प्पा समाज में इसका महत्व नहीं था, जो वैदिक काल से अलग है।"),
    # 25. Climate transition
    ("उत्तर हड़प्पा काल में पर्यावरणीय बदलावों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. कचरे के ढेरों में गैंडे और हाथी जैसे आर्द्र जलवायु के जीवों की हड्डियों का गायब होना शुष्क जलवायु को दर्शाता है।\n2. उत्तर हड़प्पा स्तरों में शुष्क परिस्थितियों में जीवित रहने वाली भेड़ और बकरियों की हड्डियों का अनुपात बढ़ गया।\nउपर्युक्त कथनों में से कौन-sa/se सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। हड्डियों के प्रकार में यह बदलाव 1900 ईसा पूर्व के आसपास मानसून के कमजोर होने और शुष्कीकरण की पुष्टि करता है।"),
    # 26. Transhumance
    ("गुजरात के खानाबदोश चरवाहा समूहों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. वे चारे की तलाश में मैदानों और पहाड़ियों के बीच मौसमी प्रवास (transhumance) करते थे।\n2. वे शहरी केंद्रों को दूध, ऊन, चमड़ा और श्रम पशु देते थे और बदले में अनाज तथा धातु के उपकरण लेते थे।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। पशुओं को बचाने के लिए ऋतुप्रवास (transhumance) होता था और वे शहरों के साथ परस्पर व्यापारिक विनिमय करते थे।"),
    # 27. Ruminant bone percentages
    ("हड़प्पा स्थलों पर प्राणि-पुरातत्वीय सांख्यिकी के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. अधिकांश शहरी स्थलों पर कुल हड्डियों में पालतू बैल, भैंस, भेड़ और बकरियों की हड्डियां 70% से 80% से अधिक हैं।\n2. हड़प्पा के आवासीय कचरे के ढेरों में जंगली हिरण और बारहसिंगा की हड्डियाँ पूरी तरह से अनुपस्थित हैं।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 1, "कथन 1 सही है। कथन 2 गलत है क्योंकि पूरक आहार के रूप में जंगली हिरणों की हड्डियां कुछ मात्रा में मिलती हैं।"),
    # 28. Marine resources Balakot
    ("बालाकोट की तटीय निर्वाह रणनीतियों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. बालाकोट में खुदाई से समुद्री मछली और समुद्री कछुओं के अवशेष भारी मात्रा में मिले हैं, जो जलीय आहार को सिद्ध करते हैं।\n2. यह स्थल समुद्री जहाजों के लिए कूबड़ वाले ऊंटों के पालन-पोषण का एक प्रमुख केंद्र था।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 1, "कथन 1 सही है। कथन 2 गलत है क्योंकि बालाकोट मछली पकड़ने और शंख कटाई का केंद्र था, ऊंटों का नहीं।"),
    # 29. Terracotta model carts
    ("सिंधु घाटी सभ्यता में परिवहन प्रणालियों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. मिट्टी के खिलौना गाड़ियों के मॉडल दिखाते हैं कि गाड़ियों को खींचने के लिए कूबड़ वाले बैलों का उपयोग होता था।\n2. खिलौना बैलगाड़ियों में ठोस (तिल्ली-रहित) पहिये होते थे, जो सड़कों पर मिले पहियों के निशानों से मेल खाते हैं।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। ठोस पहियों वाली बैलगाड़ी ही माल ढोने का मुख्य माध्यम थी, जिसकी पुष्टि खिलौने और पहियों के निशान करते हैं।"),
    # 30. Steatite seal carving
    ("हड़प्पा मुहर कला के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. मुहरों को सेलखड़ी (steatite) नामक एक नरम पत्थर पर तराशा जाता था और फिर उन्हें गर्म कर पकाया जाता था।\n2. मुहरों पर चित्रित सबसे आम जानवर कूबड़ वाला बैल (zebu) था।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 1, "कथन 1 सही है। कथन 2 गलत है क्योंकि मुहरों पर एक सींग वाला गेंडा (unicorn) सबसे आम था, बैल नहीं।"),
    # 31. Wild animals in refuse
    ("कचरे के ढेरों में मिले जंगली जानवरों के अवशेषों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. जंगली सूअर, गैंडे और हिरणों की हड्डियां दर्शाती हैं कि शहरी लोग कभी-कभी पूरक शिकार भी करते थे।\n2. भोजन के रूप में जंगली पक्षियों जैसे मोर, जंगली मुर्गियों और बत्तखों का भी सेवन किया जाता था।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। कचरे से मिले विविध अवशेष यह सिद्ध करते हैं कि पूरक आहार के रूप में जंगली पशु-पक्षियों का सेवन होता था।"),
    # 32. Composite creatures
    ("हड़प्पा मुहरों के अंकन के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. मुहरों पर कभी-कभी मिश्रित पशु (composite creatures) मिलते हैं, जैसे बैल, गेंडा और बकरे के सिरों को मिलाना।\n2. मानव चेहरे और गेंडे के सींग वाले चौपायों का चित्रण हड़प्पा की समृद्ध धार्मिक कल्पनाओं को दर्शाता है।\nउपर्युक्त कथनों में से कौन-sa/se सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। काल्पनिक और मिश्रित जानवरों का मुहरों पर चित्रण हड़प्पा संस्कृति की एक विशेष शैली थी।"),
    # 33. River turtle shells
    ("हड़प्पा में रसोई कचरे के अवशेषों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. नदियों से पकड़े गए कछुओं के खोल (shells) जिन पर जलने के निशान हैं, आहार के रूप में उनके सेवन को दर्शाते हैं।\n2. कछुओं को घरों में पालतू पशु के रूप में पाला जाता था और उन्हें मारना धार्मिक रूप से वर्जित था।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 1, "कथन 1 सही है। कथन 2 गलत है क्योंकि जले हुए खोल भोजन के हिस्से के रूप में कछुए के सेवन की पुष्टि करते हैं।"),
    # 34. Equidae family teeth
    ("कालीबंगन से प्राप्त दांतों के अवशेषों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. खुदाई से अश्व परिवार (Equidae) के जबड़े और दांतों के अवशेष प्राप्त हुए हैं।\n2. ये दंत अवशेष निश्चित रूप से यह प्रमाणित करते हैं कि राजस्थान में कृषि के लिए घरेलू घोड़ों का उपयोग होता था।\nउपर्युक्त कथनों में से कौन-sa/se सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 1, "कथन 1 सही है। कथन 2 गलत है क्योंकि इन दांतों के आधार पर घोड़े और गधे के बीच स्पष्ट अंतर करना संभव नहीं हो सका है।"),
    # 35. Domestic pets models
    ("हड़प्पा शहरों में पालतू पेट्स के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. कुत्तों के खिलौनों में उनके गले में पट्टा दिखाना सुरक्षा और पालतू होने की प्रथा को दर्शाता है।\n2. बिल्लियों के चूहे पकड़ते हुए मिट्टी के खिलौने भी प्रचुर मात्रा में खोजे गए हैं।\nउपर्युक्त कथनों में से कौन-sa/se सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 1, "कथन 1 सही है। कथन 2 गलत है क्योंकि बिल्लियों के अवशेष (पंजों के निशान) ईंट पर मिले हैं, लेकिन उनके मिट्टी के खिलौने नहीं मिले हैं।"),
    # 36. Rarity of metal sickles
    ("हड़प्पा कृषि में फसल काटने के उपकरणों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. लकड़ी के हत्थों में चर्ट (पत्थर) के फलक लगाकर बनाई गई हँसियाँ ही फसल काटने का मुख्य साधन थीं।\n2. रबी फसलों की कटाई के लिए तांबे और कांसे की हँसियों का बड़े पैमाने पर निर्माण किया जाता था।\nउपर्युक्त कथनों में से कौन-sa/se सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 1, "कथन 1 सही है। कथन 2 गलत है क्योंकि धातु की हँसियाँ अत्यंत दुर्लभ थीं, चर्ट (पत्थर) का ही उपयोग फसल कटाई में अधिक होता था।"),
    # 37. Water buffalo roles
    ("हड़प्पा में जल भैंस (Bubalus bubalis) के संबंध में निम्नलिखित कथनों पर विचार कीजिए:\n1. भैंसों का घरेलूकरण किया गया था और उनका उपयोग दूध, मांस तथा गीली मिट्टी में भारी श्रम के लिए होता था।\n2. गुजरात के शुष्क क्षेत्रों में भैंसों की हड्डियाँ कूबड़ वाले बैलों से अधिक संख्या में मिली हैं।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 1, "कथन 1 सही है। कथन 2 गलत है क्योंकि गुजरात के शुष्क क्षेत्रों में कूबड़ वाले बैल ही मुख्य थे, भैंसें जलीय या नम मैदानों में अधिक थीं।"),
    # 38. Peacock depiction
    ("हड़प्पा कला में जंगली पक्षियों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. मोर का चित्रण बर्तनों पर पेंटिंग और खिलौना मूर्तियों में बहुत अधिक मिलता है, जो उसके महत्व को दर्शाता है।\n2. मुहरों पर मोरों को देवताओं के रथ खींचते हुए चित्रित किया गया है।\nउपर्युक्त कथनों में से कौन-sa/se सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 1, "कथन 1 सही है। कथन 2 गलत है क्योंकि रथ का उपयोग ही अनुपस्थित था, और मोर का मुहरों पर रथ खींचने का कोई चित्रण नहीं है।"),
    # 39. Ivory import Mesopotamia
    ("मेसोपोटामिया के क्यूनिफॉर्म अभिलेखों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. अभिलेखों में 'मेलुहा' (सिंधु घाटी) से हाथीदांत की बनी विलासिता की वस्तुओं के आयात की सूची मिलती है।\n2. बिना तराशे हाथीदांत के बड़े दांत खाड़ी के बंदरगाहों के माध्यम से मेसोपोटामिया की कार्यशालाओं में भेजे जाते थे।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। सिंधु घाटी से निर्मित हाथीदांत की कंघियां, पिन और कच्चे दांत मेसोपोटामिया निर्यात किए जाते थे।"),
    # 40. Circular brick pens
    ("गुजरात के ग्रामीण क्षेत्रों में पशुधन प्रबंधन के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. ग्रामीण स्थलों पर पत्थर और ईंटों के वृत्ताकार बाड़े मिले हैं जो रात में भेड़-बकरियों को बांधने (corrals) के काम आते थे।\n2. ये बाड़े पालतू पशुओं को रात में बाघ और तेंदुओं जैसे हिंसक जंगली जानवरों से बचाने के लिए बनाए जाते थे।\nउपर्युक्त कथनों में से कौन-sa/se सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। ये वृत्ताकार घेरे ग्रामीण क्षेत्रों में रात में चरवाहों द्वारा पशुओं को जंगली जानवरों से सुरक्षित रखने के लिए बनाए जाते थे।"),
    # 41. Fish hook material
    ("हड़प्पा सभ्यता में मछली पकड़ने के कांटों (hooks) के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. खुदाई से मिले मछली पकड़ने के कांटे तांबे और कांसे जैसी धातुओं से बने हैं।\n2. परिपक्व हड़प्पा काल में गंगा घाटी के स्थलों से लोहे के मछली कांटों का आयात किया जाता था।\nउपर्युक्त कथनों में से कौन-sa/se सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 1, "कथन 1 सही है। कथन 2 गलत है क्योंकि हड़प्पा वासियों को लोहे का कोई ज्ञान नहीं था।"),
    # 42. Animal sacrifice
    ("हड़प्पा स्थलों पर धार्मिक अनुष्ठानों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. कालीबंगन की मिट्टी की वेदिकाओं से राख और पशुओं की हड्डियाँ मिली हैं, जो पशु बलि की ओर संकेत करती हैं।\n2. मोहनजोदड़ो की 'पशुपति मुहर' पर एक योगी को अश्वमेध (घोड़े की बलि) अनुष्ठान करते दिखाया गया है।\nउपर्युक्त कथनों में से कौन-sa/se सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 1, "कथन 1 सही है। कथन 2 गलत है क्योंकि पशुपति मुहर पर कोई बलि दृश्य नहीं है, यह ध्यानमग्न योगी और जानवरों का दृश्य है।"),
    # 43. Rigvedic vs Harappan
    ("हड़प्पा और ऋग्वैदिक समाजों के बीच अंतर के संबंध में, निम्नलिखित कथनों पर विचार कीजिए:\n1. हड़प्पा मुहरों पर बैल और एकसिंगी का दबदबा है, जबकि ऋग्वैदिक संस्कृति पूरी तरह से अश्व-केंद्रित (horse-centric) है।\n2. हड़प्पा सभ्यता मुख्य रूप से शहरी और व्यावसायिक थी, जबकि ऋग्वैदिक समाज मुख्य रूप से चरवाहा और ग्रामीण था।\nउपर्युक्त कथनों में से कौन-sa/se सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। ये दोनों कालों के बीच अर्थव्यवस्था और पशु प्राथमिकताओं में बड़े सांस्कृतिक अंतर को दर्शाते हैं।"),
    # 44. Wild ass biological
    ("कच्छ के रण के जंगली गधे (खुर) के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. जंगली गधे का वैज्ञानिक नाम 'इक्वस हेमीओनस' (Equus hemionus) है।\n2. इसकी हड्डियों की बनावट घोड़े से इतनी मिलती है कि प्राणि-पुरातत्वीय पहचान में अक्सर विवाद खड़ा होता है।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। जंगली गधे (खुर/Equus hemionus) की हड्डियों की बनावट घोड़े से बहुत अधिक मिलती है, जो सुरकोटदा विवाद का कारण है।"),
    # 45. Dog skeletons in graves
    ("हड़प्पा कब्रों में शवाधान सामग्री के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. सिंधु घाटी में मिले लगभग हर एक मानव कंकाल के पास पालतू कुत्ते का कंकाल दफन मिला है।\n2. रोपण एकमात्र ऐसा स्थल है जहाँ मालिक के शव के ठीक नीचे कुत्ते को दफनाने के साक्ष्य मिले हैं।\nउपर्युक्त कथनों में से कौन-sa/se सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "कथन 2 सही है। कथन 1 गलत है क्योंकि मनुष्य के साथ कुत्ते को दफनाने की प्रथा अत्यंत दुर्लभ थी और केवल रोपण से प्रमाणित है।"),
    # 46. Wildlife depictions environment
    ("सिंधु घाटी के प्राचीन पर्यावरण के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. मुहरों पर गैंडे और बाघ जैसे आर्द्र-भूमि के जीवों का अंकन यहाँ प्राचीन काल में नम एवं सघन वन जलवायु को दर्शाता है।\n2. मुहरों पर ऊंटों का चित्रण न होना यह प्रमाणित करता है कि सिंधु घाटी में ऊंट पूरी तरह से अनुपस्थित थे।\nउपर्युक्त कथनों में से कौन-sa/se सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 1, "कथन 1 सही है। कथन 2 गलत है क्योंकि कालीबंगन से ऊंट की हड्डियाँ मिली हैं, मुहरों पर न होना केवल शैलीगत चयन था।"),
    # 47. Bone tool manufacturing
    ("जंगली जानवरों के अवशेषों से शिल्प निर्माण के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. जंगली हिरणों (सांभर/चीतल) के सींगों (antlers) को जंगलों से एकत्र कर सुइयां, आरी और पिन बनाए जाते थे।\n2. हड़प्पा और मोहनजोदड़ो की कार्यशालाओं में सींगों को काटने और छीलने के निशान वाले साक्ष्य मिले हैं।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। हिरण के सींगों को ग्रामीण चरवाहे एकत्र कर शहरों में भेजते थे जहाँ उनसे हड्डियाँ के उपकरण बनते थे।"),
    # 50. Late Harappan pastoral shifts
    ("उत्तर हड़प्पा कालीन चरवाहा बदलावों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. बड़े शहरों के पतन के बाद पशुपालन का विकेंद्रीकरण हुआ और स्थानीय स्तर पर डेयरी का महत्व बढ़ा।\n2. गुजरात के उत्तर हड़प्पा समुदायों ने बड़े मवेशियों के बजाय भेड़ और बकरियों के पालन पर अधिक ध्यान दिया।\nउपर्युक्त कथनों में से कौन-sa/se सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। शहरों के पतन और शुष्क जलवायु के कारण चरवाहों ने छोटे तथा कम पानी में जीवित रहने वाले भेड़-बकरियों को पालना शुरू किया।"),
    # 48. Buffalo combat
    ("मुहरों पर भैंस के चित्रण के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. मुहरों पर भैंस को बाघ से मुकाबला करते हुए या किसी मानव नायक द्वारा नियंत्रित करते हुए दिखाया गया है।\n2. हड़प्पा देवताओं के मुकुटों पर भैंस के सींगों का अंकन उनके धार्मिक महत्व को दर्शाता है।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 2, "दोनों कथन सही हैं। भैंस मुहरों पर द्वंद्व दृश्यों में मिलती है और इसके सींगों का उपयोग देवताओं के सींगदार मुकुट में किया जाता था।"),
    # 49. Barter weights
    ("हड़प्पा व्यापार में विनिमय प्रणालियों के संदर्भ में, निम्नलिखित कथनों पर विचार कीजिए:\n1. वस्तुओं के तौल और विनिमय के लिए सेलखड़ी या चर्ट के अत्यंत सटीक घनाकार (cubic) बाटों का उपयोग होता था।\n2. ऊन और चमड़े जैसी वस्तुओं के व्यापार में पशुओं के चित्र अंकित धातु के सिक्कों का उपयोग किया जाता था।\nउपर्युक्त कथनों में से कौन-सा/से सही है/हैं?", ["1 केवल", "2 केवल", "1 और 2 दोनों", "न तो 1 न ही 2"], 1, "कथन 1 सही है। कथन 2 गलत है क्योंकि हड़प्पा अर्थव्यवस्था में धातु के सिक्के नहीं थे; व्यापार वस्तु-विनिमय (barter) पर आधारित था।")
]

def update_build_script():
    filepath = r"c:\Users\sande\Documents\GitHub\sjmaths-website\scratch\build_domestication_json.py"
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    # We need to replace the lists raw_practice_eng and raw_practice_hin
    # We will build Python code representations for the two new lists
    import pprint
    eng_list_str = "raw_practice_eng = [\n"
    for q, opts, ans, sol in practice_raw_eng:
        eng_list_str += f"    ({repr(q)}, {repr(opts)}, {ans}, {repr(sol)}),\n"
    eng_list_str += "]"

    hin_list_str = "raw_practice_hin = [\n"
    for q, opts, ans, sol in practice_raw_hin:
        hin_list_str += f"    ({repr(q)}, {repr(opts)}, {ans}, {repr(sol)}),\n"
    hin_list_str += "]"

    # Use regex to find and replace raw_practice_eng
    # The pattern will match raw_practice_eng = [ ... ]
    pattern_eng = r"raw_practice_eng\s*=\s*\[.*?\]"
    content = re.sub(pattern_eng, eng_list_str, content, flags=re.DOTALL)

    # Use regex to find and replace raw_practice_hin
    pattern_hin = r"raw_practice_hin\s*=\s*\[.*?\]"
    content = re.sub(pattern_hin, hin_list_str, content, flags=re.DOTALL)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    print("build_domestication_json.py successfully updated with 50 UPSC-style practice questions!")

if __name__ == "__main__":
    update_build_script()
